### ISSUE TITLE
In-Cluster Alert SOPs Design Proposal

### ISSUE THREAD

**Issue by sradco** [prometheus-operator/kube-prometheus#1048]
**What is missing?**
Provide SOPs inside the cluster, alongside alerts in order to allow i.e. the UI to show them to users as alerts appear

**Why do we need it?**
Design solution for SOPs for alert rules for both Kubernetes, kubeVirt and other operators. 
Allow adding runbooks for each alert rule.

**Environment**

* kube-prometheus version:

**Anything else we need to know?**:

**Proposed design:**
Add Prometheus annotations to every alert rules. For example:

- sop.kubevirt.io/meaning
- sop.kubevirt.io/impact
- sop.kubevirt.io/diagnosis
- sop.kubevirt.io/mitigation

For different flavors we can overwrite the diagnosis and mitigation part, with different steps to diagnose and resolve the issue.
For example:

- sop.openshift.io/diagnosis
- sop.gke.io/diagnosis
- sop.kubernets.io/diagnosis

The UI can read those annotations and use them to display useful information directly inside the UI, alongside the relevant alert that had fired
For documentation purpose, a script can be used to create a markdown doc about alerts from running inside the cluster, which can then be consumed by the docs team

Example:
The example yaml below is extending an existing Prometheus alert with the suggested annotations in order to illustrate how they should be used.

Example yaml:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
 name: olm-alert-rules
 namespace: openshift-operator-lifecycle-manager
 labels:
   prometheus: alert-rules
   role: alert-rules
spec:
 groups:
   - name: olm.failing_operators.rules
     rules:
       - alert: FailingOperator
         annotations:
           message: >-
             Failed to install Operator {{ $labels.name }} version {{
             $labels.version }}. Reason-{{ $labels.reason }}
           sop.kubevirt.io/diagnosis: "Do the following steps to understand why the servers are down\n"
           sop.kubevirt.io/impact: >-
             Having no API servers is obviously very bad for any process in need to create API
             calls. The API servers are taking care of updating the virtualization related custom
             resource definition. Without it no update can be applied to the Virtual Machines and no
             new machines can be created/deleted
           sop.kubevirt.io/meaning: >-
             This alert is based on an extrapolation of the number of running Virt API servers. It
             fires if there are no running API servers for the last 5 minutes. It's a critical alert and
             must be fixed.
           sop.kubevirt.io/mitigation: >-
             Do the following steps to fix the issue\n
           sop.openshift.io/mitigation: >-
             On OPENSHIFT you need to do the the following steps to fix the issue, go to the UI
         expr: 'csv_abnormal{phase="Failed"}'
         labels:
           severity: warning
```

By making this as Prometheus annotations, an kubectl get will become a powerful tool of understanding how to address something.

**Comment by lilic** [comment]
@prometheus-operator/kube-prometheus-reviewers @prometheus-operator/prometheus-operator-reviewers 

I asked @sradco to open this issue, so we can discuss how we want to unify the runbooks/SOP experience for all users of this 
project and document best practices so they can bring in runbooks/SOPs into their clusters in one place.

**Comment by ArthurSens** [comment]
Since #1007, all components' alerts have runbook URL and they all can be overridden with `runbookURLPattern`. Does that fulfill your needs? Usually, I see diagnosis/potential impact/mitigation as sections of a runbook 🤔.

And pardon my ignorance, what does SOP stand for?

**Comment by paulfantom** [comment]
SOP - Standard Operating Procedure otherwise known as runbook :)

Many parties/users want to have more "personalized" runbooks/sops stored in some sort of company wiki so putting all that information directly into annotations would make this hard to customize. On top of that runbooks are usually frequently adjusted to the current environment and again putting all that info into alert makes it harder on users. For those reasons, we decided to use `runbook_url` as an annotation and host runbooks in a wiki. [There is also a plan to make it a best practice for all monitoring mixins](https://monitoring.mixins.dev/#guidelines-for-alert-names-labels-and-annotations). This is also aligned with existing practices for structuring/templating alert notification messages in alertmanager. As for kube-prometheus, we have all mixins separate, and overwriting `runbook_url` can be done per component with `runbookURLPattern` as @ArthurSens pointed out.

Looking at proposed annotations those are 100% aligned with our runbook template in wiki - https://github.com/prometheus-operator/kube-prometheus/wiki/Runbooks

> By making this as Prometheus annotations, an kubectl get will become a powerful tool of understanding how to address something.

Personally, I would like to have a runbook delivered directly via alert notification and not by needing to log into a cluster. From my experience following flow is easier to follow at 3 AM (AFAIK this flow is something most SRE/Admins are familiar with):
1) get paged
2) click on a link to a runbook listed in page annotation
3) read through a runbook while logging into a cluster
4) (in case of an internal wiki) comment on runbook document during an incident if something is not going as described

By having runbook embedded into alert annotations we would need to ensure that all alerting sinks (pager duty, slack, opsgenie, etc.) can use those annotations to deliver alert in a meaningful way and we would need example alertmanager templates to show how this can be done. Otherwise, I don't see benefits.

On top of that what if I have a `PrometheusRule` with 10s of alerts? In this case, executing `kubectl get PrometheusRule <some_rule>` would give me a ton of such annotations and a person would need first to find a correct one to read how to deal with it. Unless we create a kubectl plugin specially for this.

**Comment by paulfantom** [comment]
There is also an ongoing effort to add `runbookURLPattern` to mixins to allow setting `runbook_url` pattern in an easy way ([example of how to do this for coreDNS mixin](https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/jsonnet/main.jsonnet#L427-L432)). Some mixins, like [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/add-runbook-links.libsonnet#L13) or [coredns mixin](https://github.com/povilasv/coredns-mixin/blob/master/alerts/add-runbook-links.libsonnet#L13) already natively support setting this annotation, others can be easily adapted by adding simple jsonnet snippet.

**Comment by sradco** [comment]
Having it as annotations will allow to create a script that will grep all of the information and generate the wiki automatically.
Also having a wiki is problematic in disconnected environments. It these cases having all the information available with in the code will address this issue as well.

**Comment by paulfantom** [comment]
> Having it as annotations will allow to create a script that will grep all of the information and generate the wiki automatically.

That's a one-way synchronization that can work for OpenShift. This isn't the case for kubernetes and users who have their runbooks in wikis. In this case we would need to strip down those annotations to prevent user confusion when they already have `runbook_url`.

---

> Also, Currently the runbooks links are broken at kubernetes-monitoring/kubernetes-mixin@master/runbook.md if you press on the links.

Yes and that's on kubernetes-mixin project. In the case of kube-prometheus we point to "our" wiki at https://github.com/prometheus-operator/kube-prometheus/wiki/Runbooks. And we did a simple trick to point to "create page" when the runbook doesn't exist. Example: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetes-prometheusRule.yaml#L18

**Comment by sradco** [comment]
@paulfantom I'm apologize in advance if I'm missing something, But why would we need to strip down the annotations. We can even have the wiki auto generated from the annotation and we set the runbook_url with the link to it for those that wish to use it instead. But this would gives us additional options that we can use.

I believe it can be a great advantage in cases of disconnected envs and for users that prefer to diagnose the issues from within the cluster.

**Comment by paulfantom** [comment]
If a user of kube-prometheus is already using `runbook_url` and with it pointing to their own wiki with their own procedures then having different procedures embedded into the alerts is confusing. That's why we would need to offer a way to strip those annotations away.

> I believe it can be a great advantage in cases of disconnected envs and for users that prefer to diagnose the issues from within the cluster.

I don't disagree with this. However, doing this also causes a problem for users who have their own knowledge base and would like to point to it.

**Comment by paulfantom** [comment]
I wonder why `runbook_url` cannot work in disconnected env? It isn't a cluster that needs to reach the wiki, but a user who got paged on a separate device (in most cases a mobile phone).

**Comment by sradco** [comment]
I offered a way to have different prefixes to address different flavors that can perhaps address the issue of users custom annotations. Will that work?

**Comment by paulfantom** [comment]
> I suggested a way to have different prefixes to address different flavors that can perhaps address the issue of users custom annotations. Will that work?

Sorry, I don't understand how this solves the issue of having an external knowledge base and trying to link to it from the alert?

Imagine a company with a policy of having all SOPs in Confluence (not an uncommon scenario), how do you want to solve this when SOPs are shipped via alert annotations? What if they have their own security policy and some operations need to be executed that are only valid for that company? What if said company has its own k8s flavor?

**Comment by ArthurSens** [comment]
I think that different `flavors` translate to different `platforms` when talking about kube-prometheus's architecture? Could we provide an option to those each platform to override the `runbookURLPattern` as well?

As for KubeVirt, `flavors` also translates to the Operational System of each VirtualMachineInstance, right? I might be wrong but this feels very KubeVirt specific. Could your Operator read all your current VMs and build your runbook_url from it?


I'm imagining something like this:
```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: fedora-vm
    kubevirt.io/flavor: fedora
  name: fedora-vm
spec:
.
.
.
```

You can use Prometheus relabeling to add `kubevirt.io/flavor` to your metrics and use that label to build your `runbookUrlPattern`. E.g., `https://github.com/kubevirt/kubevirt/{{ $labels.flavor}}/VirtualMachineInstanceCrashloopBackOff`

**Comment by paulfantom** [comment]
> I think that different flavors translate to different platforms when talking about kube-prometheus's architecture?

I don't see any direct connection between `platform` and `runbookURLPattern` in the case of kube-prometheus. I get the connection in case of kubeVirt, but it looks like templating this could be done on a different level as suggested.

> Could we provide an option to each platform to override the runbookURLPattern as well?

We already allow setting `runbookURLPattern` per component, for example for kubernetes alerts it would be in: `$.values.kubernetesControlPlane.mixin._config.runbookURLPattern`. We could potentially re-introduce a global parameter like `$.values.common.runbookURLPattern` and pass that value to all components but it needs some thought as we did the whole refactoring explicitly to limit global configuration and prevent accidental variable overrides.

**Comment by sradco** [comment]
By flavor I meant Kubernetes / OpenShift / gke. Its not specific to KubeVirt. And the intent is to have different mitigation according to the it.
