### ISSUE TITLE
custom endpoint missing

### ISSUE THREAD

**Issue by zouyee** [prometheus-operator/kube-prometheus#108]
**What happened?**
`v0.4.1` is not enabled `custom metrics` endpoint.
```
curl https://10.233.47.30:443/apis -k
{
  "kind": "APIGroupList",
  "groups": [
    {
      "name": "metrics.k8s.io",
      "versions": [
        {
          "groupVersion": "metrics.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "metrics.k8s.io/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": ":6443"
        }
      ]
    }
  ]
```
**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    
     v1.13.2
* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:
apiserver log
```
body was not decodable (unable to check for Status): Object 'Kind' is missing in '{\n","st        ream":"stderr","time":"2019-05-26T12:19:39.718726247Z"}
   3275 {"log":"  \"paths\": [\n","stream":"stderr","time":"2019-05-26T12:19:39.718732122Z"}
   3276 {"log":"    \"/apis\",\n","stream":"stderr","time":"2019-05-26T12:19:39.71873769Z"}
   3277 {"log":"    \"/apis/metrics.k8s.io\",\n","stream":"stderr","time":"2019-05-26T12:19:39.718743414Z"}
   3278 {"log":"    \"/apis/metrics.k8s.io/v1beta1\",\n","stream":"stderr","time":"2019-05-26T12:19:39.718749078Z"}
   3279 {"log":"    \"/healthz\",\n","stream":"stderr","time":"2019-05-26T12:19:39.718754577Z"}
   3280 {"log":"    \"/healthz/ping\",\n","stream":"stderr","time":"2019-05-26T12:19:39.718759934Z"}
   3281 {"log":"    \"/healthz/poststarthook/generic-apiserver-start-informers\",\n","stream":"stderr","time":"2019-05-26T12:19:39.718765518Z"}
   3271 {"log":"I0526 12:19:39.714603       1 round_trippers.go:438] GET https://10.233.47.30:443/apis/custom.metrics.k8s.io/v1beta1?timeout=32s 404 Not         Found in 2 milliseconds\n","stream":"stderr","time":"2019-05-26T12:19:39.716664329Z"}
```

**Comment by zouyee** [comment]
I fix it with `directxman12/k8s-prometheus-adapter-amd64:v0.5.0`

**Comment by zouyee** [comment]
@brancz PTAL ?😄

**Comment by brian-maloney** [comment]
Even using 0.5.0 I am getting NotFound on custom.metrics.k8s.io:
```
$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq
Error from server (NotFound): the server could not find the requested resource
```

Does anyone know what I'm doing wrong here?

**Comment by brancz** [comment]
cc @s-urbaniak

**Comment by s-urbaniak** [comment]
@brian-maloney custom metrics is currently not enabled in kube-prometheus, only resource metrics. As commented in https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/208#issuecomment-502018465 the `v1beta1.custom.metrics.k8s.io` is not enabled in kube-prometheus.

The reason is, that prometheus adapter currently can have issues with custom metrics in edge cases where the custom metrics discovery configuration is too broad, fetching too many metrics and exhausting memory on the adapter. We are working now on a rewrite of the prometheus adapter to address this issue amongst others.

However, if you want to enable custom metrics and configure a narrow metrics custom metric discovery configuration, you can most certainly register the adapter as a `v1beta1.custom.metrics.k8s.io` API service.

A deployment example specifically for custom metrics is available at https://github.com/DirectXMan12/k8s-prometheus-adapter/tree/8c4001831d58edaf66888d4ebb2e105191845ba4/deploy/manifests.

**Comment by kong62** [comment]
I depoy custom metrics use ansible. 3 clusters , 2 good, 1 not work.
use 0.5.0

kubectl --v=6 api-resources 
...
I0117 20:03:45.956283    4343 round_trippers.go:438] GET https://10.41.4.201:6443/apis/alicloud.com/v1beta1?timeout=32s 200 OK in 4 milliseconds
I0117 20:03:46.034589    4343 round_trippers.go:438] GET https://10.41.4.201:6443/apis/custom.metrics.k8s.io/v1beta1?timeout=32s 404 Not Found in 82 milliseconds
I0117 20:03:46.125333    4343 request.go:1145] body was not decodable (unable to check for Status): Object 'Kind' is missing in '{
  "paths": [
    "/apis",
    "/apis/metrics.k8s.io",
    "/apis/metrics.k8s.io/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/metrics",
    "/version"
  ]
}'
I0117 20:03:46.125367    4343 cached_discovery.go:78] skipped caching discovery info due to the server could not find the requested resource
...
F0117 20:03:46.128340    4343 helpers.go:114] error: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
