### ISSUE TITLE
Could not change grafana image

### ISSUE THREAD

**Issue by kaflake** [prometheus-operator/kube-prometheus#1110]
I could not change the grafana image. When I set the image to the own repository, it works with all images expected grafana. This has still the old name in the yaml-File.

```values+:: {
  common+: {
	images+: {
	  alertmanager: 'docker.own.com/quay.io/prometheus/alertmanager:v' + $.values.common.versions.alertmanager,
	  blackboxExporter: 'docker.own.com/quay.io/prometheus/blackbox-exporter:v' + $.values.common.versions.blackboxExporter,
	  grafana: 'docker.own.com/grafana/grafana:v' + $.values.common.versions.grafana,
	  ...
	},
```

**Comment by kaflake** [comment]
Same problem with quay.io/brancz/kube-rbac-proxy and jimmidyson/configmap-reload:v0.5.0

**Comment by paulfantom** [comment]
Setting those images presents 3 different bugs with different solutions:

1) We need to refactor kubernetes-grafana project to allow passing grafana image in better form. Right now it can be passed via [`imageRepos`](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/grafana.libsonnet#L7) which I agree isn't the best solution. This is a leftover from refactoring.

2) `jimmidyson/configmap-reload` is used only in blackbox_exporter and image is passed via https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/blackbox-exporter.libsonnet#L23. This should be an easy improvement to pull this image into `$.values.common.images` and allow easier setting.

3) Lack of ability to easily set `quay.io/brancz/kube-rbac-proxy` is something that should be fixed in each component. We already allow [kube-rbac-proxy component](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/kube-rbac-proxy.libsonnet) to accept `image` string, so we should follow pattern set with configmap-reloader and apply it here. Mainly to add `kubeRbacProxyImage` variable to each `defaults` variable in components which use kube-rbac-proxy (for example after [this](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/blackbox-exporter.libsonnet#L23)).

@kaflake would you like to contribute those changes or a subset of those?

**Comment by kaflake** [comment]
Okay I send separate pull-requests for this. I am not sure what I should do with required testes.
2 and 3 are straight forward.
In the solution for grafana I split the string by the ':'. This works for Grafana, because it do not use the 'v' before the version. I hope this is okay.

**Comment by paulfantom** [comment]
Thank you for your contribution! :100: I started CI jobs and it seems there are few formatting issues that will need to be fixed before merging those PRs, but overall it looks great! :+1:

**Comment by kaflake** [comment]
Okay I hope I fixed all. Next time I have to look how I can run this localy, to find this issues directly.
