### ISSUE TITLE
Advise for Kube prometheus Performance

### ISSUE THREAD

**Issue by darkgordon** [prometheus-operator/kube-prometheus#1327]
Nice to meet you all :)

I am new to this implementation of prometheus using the kubernetes manifest and I would kindly like, if you guys could give me advice about improving the use and performance of prometheus.

What do I understand about performance improvement in Prometheus?

Recently I had read a lot of post about improving the performance of prometheus thanks to these links:  [Keeping Prometheus in Shape](https://www.omerlh.info/2019/03/04/keeping-prometheus-in-shape/) and [this](https://groups.google.com/g/prometheus-users/c/St8CKdWbE74/m/bWUFjNYHBwAJ)

Highlights:

Change the scrape duration of jobs
Limiting the scrape size using sample_limit
Drop high  cardinality metrics using metric_relabel_configs with action: drop from the exporters like Node Exporter or cadvisor
Using storage.tsdb.max-block-duration flag ( I think this is not a good idea )
Setting GOGC=40(I think this is a default value

After that I proceed to install kube prometheus using the files in the manifest folder, after that I achieve starting all the prometheus services (Prometheus StateFulSet,Grafana,Node Exporters, Prometheus Operator).

I have the next questions:

Where can I find the default prometheus config.yaml , is there any configMap?
Where can I find the files about the jobs for limiting the scrape size or duration of Exporters like Node Exporters or CAdvisor?
Is there any other recommendation or advice for improving the use of memory of Prometheus 

Software used 
Kube-prometheus(latest version)
kubernetes 1.21.3

Any advice, help or documentation is welcome

**Comment by paulfantom** [comment]
kube-prometheus is a project dedicated to deploying full monitoring stack based on prometheus and largely managed by prometheus-operator. Project deploys additional components like node_exporter and kube-state-metrics to give full monitoring platform. Additionally project is deploying ready to use alerting rules and dashboards.

> Change the scrape duration of jobs

We try to set scrape interval to a level that is a good balance between performance and data granularity.

> Limiting the scrape size using sample_limit

This is not yet done as `sample_limit` was only recently merged into prometheus-operator. However since kube-prometheus is written in jsonnet and offer high level of customization, this feature can be implemented outside of the project assuming correct version of prometheus-operator is used.

> Drop high cardinality metrics using metric_relabel_configs with action

Yes, kube-prometheus is dropping metrics to prevent ingesting of less relevant metrics. For example: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetes-serviceMonitorApiserver.yaml#L13-L61

> Using storage.tsdb.max-block-duration flag ( I think this is not a good idea )

That flag is used only when using Thanos and it is set by prometheus-operator. There is no direct way to set it and we don't plan to implement it.

> Where can I find the default prometheus config.yaml , is there any configMap?

prometheus configuration is generated by prometheus-operator and is read-only (all changes will be reverted by prometheus-operator). When generated it compressed and put into a secret called `prometheus-<name>` (by default `prometheus-k8s`).

> Where can I find the files about the jobs for limiting the scrape size or duration of Exporters like Node Exporters or CAdvisor?

This is configured in ScrapeMonitor or PodMonitor. For example https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetes-serviceMonitorApiserver.yaml

> Is there any other recommendation or advice for improving the use of memory of Prometheus

Yes, https://www.robustperception.io/how-much-ram-does-prometheus-2-x-need-for-cardinality-and-ingestion

> Any advice, help or documentation is welcome

prometheus-operator getting started would be a good start - https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md

**Comment by darkgordon** [comment]
Thank you very much @paulfantom I will give it a try, thanks for your time
