### ISSUE TITLE
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by ycyxuehan** [prometheus-operator/kube-prometheus#1511]
# kubectl apply -f manifests/setup/
namespace/monitoring created
customresourcedefinition.apiextensions.k8s.io/alertmanagerconfigs.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com created
clusterrole.rbac.authorization.k8s.io/prometheus-operator created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator created
deployment.apps/prometheus-operator created
service/prometheus-operator created
serviceaccount/prometheus-operator created
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
os：              rockylinux    8.5
cri:                containerd    1.4.12
kubernetes:  1.22.4 （init by kubeadm）

**Comment by ycyxuehan** [comment]
use tag release v0.9.0 is working, close this

**Comment by nathan-vp** [comment]
This is still an issue for everybody using `kubectl apply` from the main branch (in our case using Tanka, we are even forced to do an apply instead of a create), and when a new release v0.10.0 is cut the issue will also appear there.

Can this issue be reopened?

We might need to shorten some of the description fields in this prometheuses.monitoring.coreos.com CRD.

**Comment by paulfantom** [comment]
This is the general kubernetes issue and not specific to prometheus operator. There are two recommended workarounds:
1) Create and delete objects with `kubectl create`
2) Use [server-side apply](--server-side) `kubectl apply --server-side`

Due to those existing workarounds and CD tools ability to remove this issue from existence, I don't see any need to reopen this or reduce field lengths.

---
@nathan-vp I would suggest bringing this to tanka team attention so they can implement server-side apply in their project.

**Comment by nathan-vp** [comment]
Hey @paulfantom, thanks for the quick feedback.

Workaround 1 is not ideal for us, because deleting the CRD would also remove the CR's, which would in turn remove the Prometheus Pods.

I fully agree with you that workaround 2, using server-side apply, would be the best. I will explore whether this can be added to Tanka.

Thanks again for your help!

**Comment by freemankevin** [comment]
`kubectl apply --server-side -f bundle.yaml `

**Comment by rjshk013** [comment]
I have solved the issue by entering the command inside the crds folder like below 
**kubectl apply --server-side -f crds/**
customresourcedefinition.apiextensions.k8s.io/alertmanagerconfigs.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/prometheusagents.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/scrapeconfigs.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com serverside-applied
customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com serverside-applied
