### ISSUE TITLE
Release assets differ from release branch

### ISSUE THREAD

**Issue by SixFive7** [prometheus-operator/kube-prometheus#1514]
**What happened?**

I got confused what release I should use as these are the recommendations I found:
- The documentation on the site https://prometheus-operator.dev/docs/prologue/quick-start/ states to clone master.
- The README.md suggests I should clone a specific release branch.
- The https://github.com/prometheus-operator/kube-prometheus/releases page includes assets. But also suggests using release branches. But used to suggest using head.

So as a sanity check I cloned the 0.9 release branch and also downloaded the 0.9 zip assets from the releases page. Extracting both zip files I found almost everything to be the same except for 4 files with some key differences.

**Did you expect to see some different?**

I expected the 0.9 release branch clone to be the same as the 0.9 asset files.

**How to reproduce it (as minimally and precisely as possible)**:

- Download https://github.com/prometheus-operator/kube-prometheus/archive/refs/tags/v0.9.0.zip
- Git clone the 0.9 release branch.
- Compare directory on contents ignoring file date and times.

**Anything else we need to know?**:

Maybe remove the assets if they are not to be used? Or sync up the instructions on the site and the readme if they are.

**Comment by paulfantom** [comment]
This is by design. `release` branches are rolling and they are constantly updated to ensure bugfixes are landing for older kubernetes versions. We currently support [4 release branches in addition to `HEAD`](https://github.com/prometheus-operator/kube-prometheus/blob/main/.github/workflows/versions.yaml#L12-L17) (`main` ).

What you see in the zip archive are the manifests from when `release` branch was created (without any additional updates added during backport process).

Currently, we are not releasing patch releases, hence the recommendation to use `release` branches and not tags.

More in discussion: https://github.com/prometheus-operator/kube-prometheus/discussions/1411
