### ISSUE TITLE
Alerts firing: ControllerManager, Scheduler and TargetDown

### ISSUE THREAD

**Issue by domcar** [prometheus-operator/kube-prometheus#1530]
**What did you do?**
I installed prometheus-operator and kube-prometheus using helm:
```
helm install coreos/prometheus-operator --name prometheus-operator
helm install coreos/kube-prometheus --name kube-prometheus --set rbacEnable=true
```
**What did you expect to see?**
Everything green in Alert Manager

**What did you see instead? Under which circumstances?**
Some Alerts are firing:
- K8s Scheduler
- K8S Controller
- NodeDiskRuningFull
- TargetDown

**Environment**
GKE

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	I used terraform to create the cluster on GKE

* Prometheus Operator Logs:
No Errors nor warnings

I guess somehow these targets get not scraped. Can you help me out on how to solve this issue please? Thanks

**Comment by ferpizza** [comment]
Hi,

I've been dealing with these false positives on GKE. After investigating a little, I realized that GKE doesn't expose the Kubernetes Scheduler nor the Control Manager to end users.

As we are blinded to these services, there is no need for deploying neither the Scheduler Scraper nor the Control Manager Scraper or their respective Alerts.

The easiest way of dealing with these false positive alerts is to disable the Scraping and Alerts related to services managed by GKE on the Values file of the Helm Chart.

```
kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
```

This is probably the case for other cloud providers, although I'm not sure about it.

Cheers,

**Comment by woody3549** [comment]
Hi @ferpizza,

Now I no longer receive alerts for KubeScheduler and KubeControllerManager.
Thanks.

However, a new KubeProxyDown alert now appears.
Can you please point me out what GKE exposes ?
I might have to disable it as well.

Cheers

**Comment by ferpizza** [comment]
Hello @woody3549,

I haven't found official documentation setting apart those k8s components that are exposed to end-users form the ones that are kept private for Google's management. You can make an assumption based on whether such component is key for ensuring GKE services.

`kube-proxy` is one of those components, being a critical piece in the networking of your cluster.

When I wrote my first comment I was on version 18.1.1 of the [Kube Prometheus Stack helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack), and that version did not include the `kube-proxy` alerts or scraper.

Since then I have updated to version 27.1.0, which includes the `kube-proxy` alert, and was confronted with the same issue regarding false positives.

We can solve this, and the two prior alerts, by adding the following lines to our Values file.
```
kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false
```

**Comment by woody3549** [comment]
Hello,

Ok thanks. This makes sense and is very helpful.

Regards
