### ISSUE TITLE
Prometheus CRD: Support `--web.max-connections`

### ISSUE THREAD

**Issue by saidmasoud** [prometheus-operator/kube-prometheus#1947]
**What is missing?**

An attribute within the `Prometheus` custom resource definition to enable setting the `---web.max-connections` Prometheus command-line flag. We cannot use the strategic merge patch strategy without manually defining the rest of the flags typically set by the CRD.

**Why do we need it?**

Prometheus instances handling a large number of incoming connections will struggle under load.

**Comment by slashpai** [comment]
Hello 👋🏻 , There is already issue logged for this in prometheus-operator https://github.com/prometheus-operator/prometheus-operator/issues/4850 and a PR is open https://github.com/prometheus-operator/prometheus-operator/pull/5175. Since this issue is not related to kube-prometheus and issue already present in prometheus-operator, closing this issue
