### ISSUE TITLE
Grafana database is locked

### ISSUE THREAD

**Issue by droslean** [prometheus-operator/kube-prometheus#2222]
Freshly installed kube-prometheus-stack using helm:

```console
NAME                 	NAMESPACE 	REVISION	UPDATED                                 	STATUS  	CHART                       	APP VERSION
kube-prometheus-stack	monitoring	1       	2023-09-16 17:23:26.010862703 +0300 EEST	deployed	kube-prometheus-stack-51.0.3	v0.68.0 
```

Grafana is not hanging on the login page. It is not accessible. In the logs:

```console
logger=sqlstore.transactions t=2023-09-17T09:50:48.932929871Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=0 code="database is locked"
```

Are there any solutions?

**Comment by droslean** [comment]
I found a workaround to resolve the issue:

```console
# Copy the grafana.db locally
$ kubectl cp kube-prometheus-stack-grafana-85fd4974bd-rgbj4:/var/lib/grafana/grafana.db -c grafana ./grafana.db

# Clone the db
$ sqlite3 grafana.db '.clone grafana-new.db'
$ mv grafana.db grafana-old.db
$ mv grafana-new.db grafana.db

# Copy the database back to the container
$ cp ./grafana.db kube-prometheus-stack-grafana-85fd4974bd-rgbj4:/var/lib/grafana/grafana.db -c grafana

```

**Comment by philipgough** [comment]
@droslean - you can try and deploy from main on this repo and perhaps you won't have issues with the latest versions of Grafana since there have been several updates recently. 

I am not sure what you would expect in terms of a workaround from this project? In fact you have installed everything via helm which this project does not ship or support. That would be https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

You could also try and look at the related issues in Grafana itself ([of which there are many](https://github.com/grafana/grafana/issues?q=is%3Aissue+is%3Aopen+Database+locked%2C+sleeping+then+retrying)) and try to determine why the issue occurs in your circumstances in the first place.

**Comment by droslean** [comment]
@philipgough The problem is that for some reason grafana locked its own database. This operation comes directly through Grafana. This is happening either for a specific purpose or because of a bug. For a production system, I would like to know when and how Grafana is locking the DB and for what purpose. We can keep this issue closed since some issues already exist.
