### ISSUE TITLE
prometheus-adapter pod always restart when i use custom-metrics

### ISSUE THREAD

**Issue by txjjjjj** [prometheus-operator/kube-prometheus#2284]
env:
```
main branch
eks
I'm using cilium cni, all pods use hostNetwork network mode
```

I just want to use them for hpa

```
  (import 'kube-prometheus/addons/custom-metrics.libsonnet') +
  (import 'kube-prometheus/addons/external-metrics.libsonnet') +
```

Using prometheus-adapter, is there a more detailed guide?

```
 ✗ k get apiService | grep metrics
v1beta1.custom.metrics.k8s.io          monitoring/prometheus-adapter   False (FailedDiscoveryCheck)   9m46s
v1beta1.external.metrics.k8s.io        monitoring/prometheus-adapter   False (FailedDiscoveryCheck)   9m46s
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True                           9m47s
v1beta2.custom.metrics.k8s.io          monitoring/prometheus-adapter   False (FailedDiscoveryCheck)   9m46s

```

**Comment by pschulten** [comment]
same here

**Comment by Danny5487401** [comment]
same here .
![image](https://github.com/prometheus-operator/kube-prometheus/assets/64348131/e1693126-8844-4f6d-b829-40afa377b25e)
![image](https://github.com/prometheus-operator/kube-prometheus/assets/64348131/0bb6db02-dba1-4aea-a389-bf072e8855c2)

**Comment by sabe-soptim** [comment]
Seconded. Gradually increasing the memory resource/limits helped with the restarts, that were caused by OOMKills.
Another thing that significantly decreased my RAM usage was setting  
```yaml
rules:
  default: false
```  
in the Helm Release.  
Not setting this value leads to the adapter firing 6 default catch-all rules matching every Prometheus metric, which causes the RAM to spike.   
Check out [this discussion](https://github.com/rancher/rancher/issues/30697#issuecomment-4345044987) for more info about this.
