### ISSUE TITLE
support grafana crd

### ISSUE THREAD

**Issue by txjjjjj** [prometheus-operator/kube-prometheus#2343]
any plans to support grafana crd？

**Comment by aisbaa** [comment]
I would also like to see [grafana operator](https://github.com/grafana/grafana-operator/tree/master) part of kube-promehteus. Prometheus part is top notch, its supper easy to add new monitor rules/alerts bundled next application manifest. Would be awesome to have the same for grafana, so that dashboard would be next to app manifests.

Here's the example directory structure we use with [kustomize](https://kustomize.io/):
```
ssh-bastion
├── alerts
│   ├── alertingRules.yaml
│   └── kustomization.yaml
├── base
│   ├── deployment.yaml
│   ├── kustomization.yaml
│   ├── service.yaml
│   └── trusted_user_ca
├── cluster_0
│   └── kustomization.yaml (includes base and alerts as bases)
├── cluster_1
│   └── kustomization.yaml (same as cluster_0, includes base and alerts as bases)
...
```

It would be incredibly convenient to add `dashboards` or `grafana` folder next to `alerts`.
