### ISSUE TITLE
Build not generating setup manifests files for EBS

### ISSUE THREAD

**Issue by roshan8** [prometheus-operator/kube-prometheus#405]
**What happened?**
We tried compiling the project to get the manifests for using EBS as PVC.
`./build.sh examples/prometheus-pvc.jsonnet`

This generated manifests in /manifests, However /manifests/setup is empty

* Prometheus Operator version: v0.3.0

* Kubernetes cluster kind: kops

**Comment by pgier** [comment]
Looks like I broke this in #258.  All the necessary files should be available in the manifests directory, so as a workaround you should be able to just `kubectl apply` that directory, although you will likely need to apply multiple times so that the custom resources are recognized.  Longer term I'll try to fix this so that these examples work again.

**Comment by roshan8** [comment]
Thanks, It worked @pgier 
2 things that i noticed
- It's not creating the monitoring namespace
- Since all manifests are there in a single place, Execution ran into race condition(https://github.com/coreos/prometheus-operator/issues/1866), So I had to apply manifests 2 times.

**Comment by paulfantom** [comment]
Closing due to staleness. Please reopen if you think this is still relevant.
