### ISSUE TITLE
no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1

### ISSUE THREAD

**Issue by arpita-hub** [prometheus-operator/kube-prometheus#561]
**What happened?**

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```
while running kubectl create -f manifests/
![reeeeee](https://user-images.githubusercontent.com/52378141/83871085-0bc4f900-a74d-11ea-91c4-9530845010ae.png)

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:
![reeeeee](https://user-images.githubusercontent.com/52378141/83871034-ef28c100-a74c-11ea-9bbb-8f3f39e89090.png)

**Comment by brancz** [comment]
As the [quickstart](https://github.com/coreos/kube-prometheus#quickstart) mentions, you need to first create the contents of the `setup/` directory.

**Comment by SarasaGunawardhana** [comment]
This issue was fixed after adding below CRDs. 

Link : [Helm fails to create CRDs](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#helm-fails-to-create-crds)

kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.43/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml

**Comment by paulfantom** [comment]
Closing as this appears to be answered. Please reopen if you think this is still relevant.
