### ISSUE TITLE
How to customize /etc/prometheus/config_out/ prometheus. env.yaml?

### ISSUE THREAD

**Issue by autumn1023** [prometheus-operator/kube-prometheus#647]
How to customize /etc/prometheus/config_out/ prometheus. env.yaml  I want to add ,I want to add a job_name  Thank you .
![image](https://user-images.githubusercontent.com/19710386/90230132-a592db80-de4b-11ea-8e28-09766a2016f3.png)

**Comment by olegmayko** [comment]
in order to monitor additional namespace you need to follow [this](https://github.com/prometheus-operator/kube-prometheus#adding-additional-namespaces-to-monitor). If there is a need to monitor something outside the cluster, you may check [this](https://github.com/prometheus-operator/prometheus-operator/tree/master/example/additional-scrape-configs)

**Comment by autumn1023** [comment]
@olegmayko   thank you !
